### ISSUE TITLE
macOS broken

### ISSUE THREAD

**Issue by henryiii** [conda-forge/numpy-feedstock#126]
The recent update to gfortran version 4 broke conda-forge numpy on macOS. The following now fails:

```bash
conda create -n numpytest numpy -c conda-forge
conda activate numpytest
python -C "import numpy"
```

Numpy -> blas is looking for `libgfortran.3.dylib`, but `libgfortran.4.dylib` is the only one provided.

Forcing libgfortran=3 fixes the issue.

See the issue I opened here, as well: https://github.com/conda-forge/gfortran_impl_osx-64-feedstock/issues/9

**Comment by duncanmmacleod** [comment]
I also see this on travis-ci for a downstream feedstock [[link](https://travis-ci.org/conda-forge/lscsoft-glue-feedstock/jobs/489917016)].

**Comment by beckermr** [comment]
This is fixed!

**Comment by rgommers** [comment]
was fixed by https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/11 (took a while to find that one ...), closing

**Comment by tengjuilin** [comment]
In macOS, the problem still exists. The code

```
conda create -n numpytest numpy -c conda-forge
conda activate numpytest
python -c "import numpy"
```

gives ImportError of

```
Traceback (most recent call last):
  File "/opt/miniconda3/envs/numpytest/lib/python3.10/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/opt/miniconda3/envs/numpytest/lib/python3.10/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/opt/miniconda3/envs/numpytest/lib/python3.10/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dlopen(/opt/miniconda3/envs/numpytest/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so, 0x0002): Library not loaded: '@rpath/libgcc_s.1.1.dylib'
  Referenced from: '/opt/miniconda3/envs/numpytest/lib/libgfortran.5.dylib'
  Reason: tried: '/opt/miniconda3/envs/numpytest/lib/libgcc_s.1.1.dylib' (no such file), '/opt/miniconda3/envs/numpytest/lib/libgcc_s.1.1.dylib' (no such file), '/opt/miniconda3/envs/numpytest/lib/libgcc_s.1.1.dylib' (no such file), '/opt/miniconda3/envs/numpytest/lib/python3.10/site-packages/numpy/core/../../../../libgcc_s.1.1.dylib' (no such file), '/opt/miniconda3/envs/numpytest/lib/python3.10/site-packages/numpy/core/../../../../libgcc_s.1.1.dylib' (no such file), '/opt/miniconda3/envs/numpytest/bin/../lib/libgcc_s.1.1.dylib' (no such file), '/opt/miniconda3/envs/numpytest/bin/../lib/libgcc_s.1.1.dylib' (no such file), '/usr/local/lib/libgcc_s.1.1.dylib' (no such file), '/usr/lib/libgcc_s.1.1.dylib' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/miniconda3/envs/numpytest/lib/python3.10/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/opt/miniconda3/envs/numpytest/lib/python3.10/site-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/opt/miniconda3/envs/numpytest/bin/python"
  * The NumPy version is: "1.23.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/opt/miniconda3/envs/numpytest/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so, 0x0002): Library not loaded: '@rpath/libgcc_s.1.1.dylib'
  Referenced from: '/opt/miniconda3/envs/numpytest/lib/libgfortran.5.dylib'
  Reason: tried: '/opt/miniconda3/envs/numpytest/lib/libgcc_s.1.1.dylib' (no such file), '/opt/miniconda3/envs/numpytest/lib/libgcc_s.1.1.dylib' (no such file), '/opt/miniconda3/envs/numpytest/lib/libgcc_s.1.1.dylib' (no such file), '/opt/miniconda3/envs/numpytest/lib/python3.10/site-packages/numpy/core/../../../../libgcc_s.1.1.dylib' (no such file), '/opt/miniconda3/envs/numpytest/lib/python3.10/site-packages/numpy/core/../../../../libgcc_s.1.1.dylib' (no such file), '/opt/miniconda3/envs/numpytest/bin/../lib/libgcc_s.1.1.dylib' (no such file), '/opt/miniconda3/envs/numpytest/bin/../lib/libgcc_s.1.1.dylib' (no such file), '/usr/local/lib/libgcc_s.1.1.dylib' (no such file), '/usr/lib/libgcc_s.1.1.dylib' (no such file)
```

The solution found in https://github.com/numpy/numpy/issues/12970 solves the problem with

```
conda uninstall numpy
conda install numpy
```
but if the environment is created with `environment.yml`, the environment will not be well-configured upon creation, which may lead to reproducibility issues.

**Comment by rgommers** [comment]
Can you please open a new issue instead @tengjuilin? This was fixed, there may be a reoccurrence or a different issue which shows the same traceback, either way a new issue is more useful here.
